language: node_js
node_js:
  - '8'
  - '10'
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - test ! -d node_modules || npm prune
scripts:
  - npm run test
  - npm run build
after_script:
  - test $TRAVIS_NODE_VERSION != '10' && sonar-scanner
notifications:
  email:
    recipients:
    - dragos.cirjan+glasswingjs@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "glasswingjs"
    token:
      secure: "egXGzrW7w2xqevJDt1Gdqt2eKSTxeq7HiLN/gSRjF2qSMPbJ4ldhYK5mUWTW791Ya9e39+NHyhyW5C6bZLeK1rjcKTx0xpBgqPFgKhrOYi/Zjaf8Ygot3T9k1CepbupElC6xqvQnx92lQ3VN2GfYfKtNLHk5diVlB3ZmU+wqrN0Wd4cJ7wbmdrlOwDWRjxs6RS0r/KXBRszboR0nUR4bI04eg6gMOrEsnNPHJgVTrKVOivDDGOhY7m6x9Uposn/kInWEnJxuUq/kc9V8kib5dZ5UAVHP1junRN00sSM33G+z0z9nIWEqdu07GkAIiUdfnSy2Xv5KN94bvIMPY9xOo4oIi326s0Gn5dfRHHNHoeCNDqPA7Z7ZASHXOEsIxVHbd3CKTSK8UYjhNmGZ8oj+kZ/JHkH1WUYB9nUhtOjOfCyR53cqZxpLDYQrkMIPPyQ+HtIgqFmZ3YLtKRJly0ibAUvnE3MWVckmcTzNaOhugZnoe/BnY0w9sB35ucOaIKPmRNdb95m8caYrPaxH2kPoWK+99L3nb4IEp0OcbwkQuJhrzn5haTaam0fBhEUdd2CfdTuSu1LCOWJzqv5jGS+mPm4b3gMLqRbdSPrtMpRpfuBuse847RwO38T+VL4AzX/PfL6HRkgHuBzVlprSKN7pLLR3N5aLIgKrmgPOtdXC3V8="


